name: Идея
description: Предложить фичу или улучшение
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: Что предлагаешь
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Зачем
      description: Какую задачу это решает и как ты обходишься сейчас.
    validations:
      required: true
